### ISSUE TITLE
v2 actions start back at 0.0.1 when working with v1 actions

### ISSUE THREAD

**Issue by MatthewFlamm** [zwaldowski/semver-release-action#12]
I was using v1 successfully until I had `set-env` errors.  Now with using v2, the tags have started over at 0.0.1.  Do I need to change something in my workflow to fix this?

[Workflow file](https://github.com/MatthewFlamm/pytest-homeassistant-custom-component/blob/9f2ac4f45ad6252ae5738fc6c2ad727af0d88f2c/.github/workflows/make_release.yml#L11-L16)

Logs when running action.
```
Run zwaldowski/semver-release-action@v2
  with:
    dry_run: true
    bump: patch
    github_token: ***
    per_branch: false
Getting list of tags from branch
/usr/bin/git fetch --tags --quiet
/usr/bin/git tag --no-column --merged
Using latest tag "0.0.0" with identifier ""
Using tag prefix ""
Result: "0.0.1" (tag: "0.0.1")
```

**Comment by zwaldowski** [comment]
Hey, @MatthewFlamm. Sorry about that. I've updated the v2 tag, can you try running with debug logs as [described here](<https://github.com/actions/toolkit/blob/main/docs/action-debugging.md#step-debug-logs>) and letting me know if it's still having trouble? Thanks!

**Comment by MatthewFlamm** [comment]
This seems to be fixed.  Thanks for the quick turnaround!
