### ISSUE TITLE
Error: octokit.git.listRefs is not a function

### ISSUE THREAD

**Issue by relu** [zwaldowski/semver-release-action#14]
Seems the latest version release has a regressions:

Config:
```
  with:
    dry_run: true
    bump: minor
    prefix: v
    github_token: ***
    per_branch: false
Getting list of tags from repository
Error: octokit.git.listRefs is not a function
```

**Comment by zwaldowski** [comment]
Hey, @relu. Sorry about that. I've updated the v2 tag, can you let me know with logs if it's still having trouble? Thanks!

**Comment by relu** [comment]
Looks good now, thank you for the swift resolve! :100:
