### ISSUE TITLE
Please add example when different commit, PR contains: fix, feature. 

### ISSUE THREAD

**Issue by patsevanton** [zwaldowski/semver-release-action#20]
Hello! Thanks for semver-release-action!
I try use your semver github action.
But i dont see example.
For example, how update patch version if commit have 'fix' string ?
For example, how update minor version if commit have 'feature' string ?

**Comment by zwaldowski** [comment]
There is an example in the [README](https://github.com/zwaldowski/semver-release-action#example-usage).

Matching the commit message is not part of this action, but is part of Github Actions itself. See [here](https://dev.to/mliakos/conditional-github-action-based-on-commit-message-2l02). You can ask on the [GitHub forums](https://support.github.com/features/actions) if you need more help with that.

**Comment by patsevanton** [comment]
Matching the commit message is not part of this action - i understend. Thanks!
