### ISSUE TITLE
Not documented input `per_branch`

### ISSUE THREAD

**Issue by ViacheslavKudinov** [zwaldowski/semver-release-action#34]
Hello @zwaldowski 
there is input `per_branch` which is for some reason not mentioned in Readme file https://github.com/zwaldowski/semver-release-action/blob/main/action.yml#L7. 
As I see it's been there since 2020.
Is it any reason why that wasn't added to the documentation or just was missed?

**Comment by zwaldowski** [comment]
This was an oversight from #8. See [e1fc5ff](https://github.com/zwaldowski/semver-release-action/commit/e1fc5ff55aaf21b1a27b431346ab0e869640cfb7).

**Comment by ViacheslavKudinov** [comment]
Thank you @zwaldowski
